Repository tomrtk/fish-code, pull requests merged in 2021-07, with the labels that each got.

#53 fix: parsing of command line arguments
  src/core/main.py
  src/detection/main.py
  src/nina/run.py
  src/tracing/main.py
Labels: bug, code::backend, done

#50 ci(coverage): use codecov
  .github/workflows/commitlint.yml
  .github/workflows/tests.yaml
  README.md
  pyproject.toml
  requirements-dev.txt
  setup.cfg
Labels: annoyance, ci, code::quality

#55 Create codeql-analysis.yaml
  .github/workflows/codeql-analysis.yaml
Labels: ci, code::quality, enhancement

#68 fix: broken Makefile from #50
  Makefile
Labels: bug, done

#74 chore(tox): remove usedevelop
  pyproject.toml
Labels: bug, ci, done

#75 Stat calc
  src/core/api/api.py
  src/core/api/schema.py
  src/core/api/utils.py
  src/core/model.py
  tests/unit/core/integration/test_api.py
  tests/unit/core/integration/test_schema.py
  tests/unit/core/unit/test_api_helpers.py
  tests/unit/core/unit/test_job.py
  tests/unit/core/unit/test_schema.py
Labels: code::core, done

#95 fix(tracing): fix bug resulting in objects leaking between jobs
  src/tracing/tracker.py
  tests/integration/test_data/test-abbor-small[2021-01-02_00-00-00]-000.mp4
  tests/integration/test_regression.py
Labels: bug, code::tracking

#100 ci: added release workflow
  .github/workflows/release.yaml
Labels: ci, enhancement

#115 ci(lfs): attempt at cache lfs to reduce bandwidth
  .github/workflows/tests.yaml
Labels: annoyance, ci, doing, performance

#139 refactor(ui): disable global form reset
  src/ui/projects/templates/projects/job_new.html
  src/ui/projects/templates/projects/project_new.html
  src/ui/static/dist/css/style.min.css
  src/ui/tailwind.config.js
Labels: annoyance, code::ui, done, ui::logic
