Repository tomrtk/fish-code, pull requests merged in 2023-01, with the labels that each got.

#540 style: tweak editorconfig
  .editorconfig
Labels: annoyance, code::quality

#544 ci: support manual trigger
  .github/workflows/tests.yaml
Labels: ci

#546 chore: fix pre-commit
  .pre-commit-config.yaml
Labels: code::quality

#548 fix: fix mutable arguments and abstract class
  src/core/model.py
  src/tracing/tracker.py
  src/ui/projects/api.py
Labels: code::quality, done

#550 fix: update flask & uvicorn
  setup.cfg
  src/core/main.py
Labels: done, dependencies

#551 fix: update flask
  setup.cfg
  src/ui/projects/projects.py
Labels: done, dependencies

#534 feat: convert to pyproject.yaml
  .flake8
  .pre-commit-config.yaml
  .prettierignore
  pyproject.toml
  setup.cfg
Labels: code::quality, done

#552 test: use python 3.9 & 3.10 for testing
  .github/workflows/tests.yaml
  README.md
  pyproject.toml
Labels: done, tests

#553 chore: remove makefile & references to it
  Makefile
  README.md
Labels: documentation, annoyance

#557 release v1.2.0
  .github/workflows/release.yaml
Labels: ci, meta
